from __init__ import *
exec(open("__init__.py").read())

global liste_obstacles, liste_blocs, liste_regles, taille, grille, liste_liste_objets

#bloc = Bloc(False, False, True, "IS", "is", (2,2))
#liste_blocs.append(bloc)
#bloc = Bloc(False, False, True, "IS", "is", (3,1))
#liste_blocs.append(bloc)
bloc = Bloc("adj", "STOP", "stop", (25,7))
liste_blocs.append(bloc)
#bloc = Bloc(False, True, False, "    BAD\nCHAMPIS", "badchampi", (2,1))
#liste_blocs.append(bloc)

liste_blocs.append(Bloc("noun", "ANNE", "anne", (5,4)))
liste_blocs.append(Bloc("adj", "YOU", "you", (7,4)))
liste_blocs.append(Bloc("verb", "IS", "is", (6,4)))
liste_blocs.append(Bloc("noun", "WALL", "wall", (0,0)))
liste_blocs.append(Bloc("verb", "IS", "is", (0,1)))
liste_blocs.append(Bloc("adj","STOP", "stop", (0,2)))
liste_blocs.append(Bloc("noun", "   GOOD\nCHAMPI", "good champi", (4,8)))
liste_blocs.append(Bloc("verb", "IS", "is", (4,9)))
liste_blocs.append(Bloc("adj", "PUSH", "push", (4,10)))
liste_blocs.append(Bloc("noun", "GRASS", "grass", (13,6)))
liste_blocs.append(Bloc("verb", "IS", "is", (14,7)))
liste_blocs.append(Bloc("adj", "GREENER", "greener", (15,8)))
liste_blocs.append(Bloc("noun", "    BAD\nCHAMPI", "bad champi", (7,10)))
liste_blocs.append(Bloc("verb", "IS", "is", (7,11)))
liste_blocs.append(Bloc("adj", "SHUT", "shut", (7,12)))

#liste_blocs.append(Bloc("noun", "ANNE", "anne", (15,4)))
#liste_blocs.append(Bloc("noun", "ANNE", "anne", (17,4)))
#liste_blocs.append(Bloc("verb", "IS", "is", (16,4)))
liste_blocs.append(Bloc("noun", "   GOOD\nCHAMPI", "good champi", (17,5)))
liste_blocs.append(Bloc("verb", "IS", "is", (17,6)))
liste_blocs.append(Bloc("adj", "OPEN", "open", (17,7)))

#obstacles
liste_obstacles.append(Obstacle("good champi", (7, 6)))
liste_obstacles.append(Obstacle("bad champi", (9, 6)))
liste_obstacles.append(Obstacle("anne", (11,2)))
liste_obstacles.append(Obstacle("grass", (0,3)))
liste_obstacles.append(Obstacle("grass", (1,0)))
liste_obstacles.append(Obstacle("grass", (1,1)))
liste_obstacles.append(Obstacle("grass", (1,2)))
liste_obstacles.append(Obstacle("grass", (1,3)))


for j in range(16):
    for i in range(22-j//2, 25-j//2):
        liste_obstacles.append(Obstacle("grass", (i,j)))

liste_obstacles.append(Obstacle("wall", (13,0)))
liste_obstacles.append(Obstacle("wall", (13,1)))
liste_obstacles.append(Obstacle("wall", (13,2)))
liste_obstacles.append(Obstacle("wall", (13,3)))
liste_obstacles.append(Obstacle("wall", (13,4)))
liste_obstacles.append(Obstacle("wall", (12,4)))
liste_obstacles.append(Obstacle("wall", (11,4)))
liste_obstacles.append(Obstacle("wall", (10,4)))
liste_obstacles.append(Obstacle("wall", (9,4)))
liste_obstacles.append(Obstacle("wall", (9,3)))
liste_obstacles.append(Obstacle("wall", (9,5)))
liste_obstacles.append(Obstacle("wall", (8,5)))
liste_obstacles.append(Obstacle("wall", (9,1)))
liste_obstacles.append(Obstacle("wall", (9,0)))
liste_obstacles.append(Obstacle("wall", (10,0)))
liste_obstacles.append(Obstacle("wall", (11,0)))
liste_obstacles.append(Obstacle("wall", (12,0)))
liste_obstacles.append(Obstacle("wall", (4,5)))
liste_obstacles.append(Obstacle("wall", (3,5)))
liste_obstacles.append(Obstacle("wall", (3,4)))
liste_obstacles.append(Obstacle("wall", (3,3)))
liste_obstacles.append(Obstacle("wall", (3,2)))
liste_obstacles.append(Obstacle("wall", (3,1)))
liste_obstacles.append(Obstacle("wall", (3,0)))
liste_obstacles.append(Obstacle("wall", (3,6)))
liste_obstacles.append(Obstacle("wall", (3,7)))
liste_obstacles.append(Obstacle("wall", (3,8)))
liste_obstacles.append(Obstacle("wall", (4,7)))
liste_obstacles.append(Obstacle("wall", (5,7)))
liste_obstacles.append(Obstacle("wall", (6,7)))
liste_obstacles.append(Obstacle("wall", (7,7)))
liste_obstacles.append(Obstacle("wall", (8,7)))

liste_obstacles.append(Obstacle("wall", (9,7)))
liste_obstacles.append(Obstacle("wall", (5,8)))
liste_obstacles.append(Obstacle("wall", (8,0)))
liste_obstacles.append(Obstacle("wall", (7,0)))
liste_obstacles.append(Obstacle("wall", (6,0)))
liste_obstacles.append(Obstacle("wall", (5,0)))
liste_obstacles.append(Obstacle("wall", (4,0)))
